# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/marina/Documents/TFM_desarrollo/tfm_curvature

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/marina/Documents/TFM_desarrollo/tfm_curvature

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/marina/Documents/TFM_desarrollo/tfm_curvature/CMakeFiles /mnt/c/Users/marina/Documents/TFM_desarrollo/tfm_curvature/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/marina/Documents/TFM_desarrollo/tfm_curvature/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named laplacian_smooth

# Build rule for target.
laplacian_smooth: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 laplacian_smooth
.PHONY : laplacian_smooth

# fast build rule for target.
laplacian_smooth/fast:
	$(MAKE) -f CMakeFiles/laplacian_smooth.dir/build.make CMakeFiles/laplacian_smooth.dir/build
.PHONY : laplacian_smooth/fast

#=============================================================================
# Target rules for targets named mean_curvature

# Build rule for target.
mean_curvature: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mean_curvature
.PHONY : mean_curvature

# fast build rule for target.
mean_curvature/fast:
	$(MAKE) -f CMakeFiles/mean_curvature.dir/build.make CMakeFiles/mean_curvature.dir/build
.PHONY : mean_curvature/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f glad/CMakeFiles/glad.dir/build.make glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f glfw/src/CMakeFiles/glfw.dir/build.make glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

src/laplacian.o: src/laplacian.cpp.o

.PHONY : src/laplacian.o

# target to build an object file
src/laplacian.cpp.o:
	$(MAKE) -f CMakeFiles/laplacian_smooth.dir/build.make CMakeFiles/laplacian_smooth.dir/src/laplacian.cpp.o
.PHONY : src/laplacian.cpp.o

src/laplacian.i: src/laplacian.cpp.i

.PHONY : src/laplacian.i

# target to preprocess a source file
src/laplacian.cpp.i:
	$(MAKE) -f CMakeFiles/laplacian_smooth.dir/build.make CMakeFiles/laplacian_smooth.dir/src/laplacian.cpp.i
.PHONY : src/laplacian.cpp.i

src/laplacian.s: src/laplacian.cpp.s

.PHONY : src/laplacian.s

# target to generate assembly for a file
src/laplacian.cpp.s:
	$(MAKE) -f CMakeFiles/laplacian_smooth.dir/build.make CMakeFiles/laplacian_smooth.dir/src/laplacian.cpp.s
.PHONY : src/laplacian.cpp.s

src/main_mean_curvature.o: src/main_mean_curvature.cpp.o

.PHONY : src/main_mean_curvature.o

# target to build an object file
src/main_mean_curvature.cpp.o:
	$(MAKE) -f CMakeFiles/mean_curvature.dir/build.make CMakeFiles/mean_curvature.dir/src/main_mean_curvature.cpp.o
.PHONY : src/main_mean_curvature.cpp.o

src/main_mean_curvature.i: src/main_mean_curvature.cpp.i

.PHONY : src/main_mean_curvature.i

# target to preprocess a source file
src/main_mean_curvature.cpp.i:
	$(MAKE) -f CMakeFiles/mean_curvature.dir/build.make CMakeFiles/mean_curvature.dir/src/main_mean_curvature.cpp.i
.PHONY : src/main_mean_curvature.cpp.i

src/main_mean_curvature.s: src/main_mean_curvature.cpp.s

.PHONY : src/main_mean_curvature.s

# target to generate assembly for a file
src/main_mean_curvature.cpp.s:
	$(MAKE) -f CMakeFiles/mean_curvature.dir/build.make CMakeFiles/mean_curvature.dir/src/main_mean_curvature.cpp.s
.PHONY : src/main_mean_curvature.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... laplacian_smooth"
	@echo "... mean_curvature"
	@echo "... glad"
	@echo "... glfw"
	@echo "... src/laplacian.o"
	@echo "... src/laplacian.i"
	@echo "... src/laplacian.s"
	@echo "... src/main_mean_curvature.o"
	@echo "... src/main_mean_curvature.i"
	@echo "... src/main_mean_curvature.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

